openapi: 3.0.0
info:
  title: Example Carrier API
  version: 1.0.0
  description: API for handling claims and generating estimates.
servers:
  - url: http://localhost:8290
    description: Local server
paths:
  /claim/submit/simple:
    post:
      summary: Submit a simple claim without attachment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimSubmission'
            example:
              claimReference: "CLM1234567"
              dateSubmitted: "2024-06-06T12:00:00Z"
              customerReference: "CUST78910"
              policyID: "112233"
              customerProfile:
                id: "123"
                name: "John Doe"
                address: "1234 Elm St, Springfield, USA"
              customerContact:
                email: "johndoe@example.com"
                phone: "555-1234"
              claimType: "Property Damage"
              propertyDetails:
                reference: "PROP101112"
                address: "1234 Elm St, Springfield, USA"
                type: "Residential"
                location:
                  latitude: 34.052235
                  longitude: -118.243683
              lossDetails:
                dateOfLoss: "2024-06-01T10:00:00Z"
                typeOfLoss: "Fire Damage"
                estimatedLoss: "$5000"
                attachments: "fire_damage_photo.jpg"
      responses:
        '200':
          description: Simple claim submitted successfully
          content:
            text/plain:
              schema:
                type: string
                example: simple claim submitted successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid claim data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: internal server error

components:
  schemas:
    ClaimSubmission:
      type: object
      properties:
        claimReference:
          type: string
        dateSubmitted:
          type: string
        customerReference:
          type: string
        policyID:
          type: string
        customerProfile:
          $ref: '#/components/schemas/CustomerProfile'
        customerContact:
          $ref: '#/components/schemas/CustomerContact'
        claimType:
          type: string
        propertyDetails:
          $ref: '#/components/schemas/PropertyDetails'
        lossDetails:
          $ref: '#/components/schemas/LossDetails'
    CustomerProfile:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
    CustomerContact:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string
    Location:
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
    PropertyDetails:
      type: object
      properties:
        reference:
          type: string
        address:
          type: string
        type:
          type: string
        location:
          $ref: '#/components/schemas/Location'
    LossDetails:
      type: object
      properties:
        dateOfLoss:
          type: string
        typeOfLoss:
          type: string
        estimatedLoss:
          type: string
        attachments:
          type: string
    ContractLookupRequest:
      type: object
      properties:
        claimReference:
          type: string
        customerReference:
          type: string
        policyID:
          type: integer
    ContractLookupResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        routeTo:
          type: string
    EstimationRequest:
      type: object
      properties:
        policyID:
          type: integer
        claimReference:
          type: string
        customerReference:
          type: string
        customerProfile:
          $ref: '#/components/schemas/CustomerProfile'
        lossDetails:
          $ref: '#/components/schemas/LossDetails'
    EstimationResponse:
      type: object
      properties:
        status:
          type: string
        estimatedRepairCost:
          type: string
        vendorAssigned:
          type: string
        expectedCompletionDate:
          type: string
    FireDamageRepairRequest:
      type: object
      properties:
        claimReference:
          type: string
        customerReference:
          type: string
        propertyDetails:
          $ref: '#/components/schemas/PropertyDetails'
        typeOfServiceRequested:
          type: string
        dateOfServiceRequested:
          type: string
    FireDamageRepairResponse:
      type: object
      properties:
        status:
          type: string
        serviceDate:
          type: string
        serviceProvider:
          type: string
    FileAttachment:
      type: object
      properties:
        fileName:
          type: string
        content:
          type: string
          format: binary
        contentType:
          type: string
