openapi: 3.0.0
info:
  title: Claim Estimate API
  version: 1.0.0
  description: API for handling claims and generating estimates.
servers:
  - url: http://localhost:8082
    description: Local server
paths:
  /estimate:
    post:
      summary: Estimate Generation
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                attachments:
                  type: string
                  format: binary
                  description: The file to be uploaded
                claim:
                  type: string
                  description: JSON payload with claim details
              required:
                - attachments
                - claim
      responses:
        '200':
          description: Successfully generated estimate
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Estimate Generated
                  estimatedRepairCost:
                    type: string
                    example: $4500
                  vendorAssigned:
                    type: string
                    example: DigiFact
                  expectedCompletionDate:
                    type: string
                    example: 2024-06-20T00:00:00Z
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: File upload error
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unable to determine file size
components:
  schemas:
    Claim:
      type: object
      properties:
        claimReference:
          type: string
        customerReference:
          type: string
        customerProfile:
          $ref: '#/components/schemas/CustomerProfile'
        policyID:
          type: integer
        lossDetails:
          $ref: '#/components/schemas/LossDetails'
    CustomerProfile:
      type: object
      properties:
        id:
          type: string
    LossDetails:
      type: object
      properties:
        dateOfLoss:
          type: string
        typeOfLoss:
          type: string
        estimatedLoss:
          type: string
        attachments:
          type: string
